### ISSUE TITLE
Base and Conditions

### ISSUE THREAD

**Issue by mepalacios** [robertmurer/todosalacancha#176]
Hello Deba, please in Base and Conditions, the down scroll arrow does not work
![base](https://user-images.githubusercontent.com/38966922/39663047-01dc060c-503a-11e8-8547-d47040afecec.JPG)

**Comment by carlos-segovia** [comment]
In Firefox works fine because dont have the arrow.
![image](https://user-images.githubusercontent.com/34341691/39680518-e530f992-5177-11e8-9064-968fbd489ed7.png)
In Chrome words fine the arrow:
![image](https://user-images.githubusercontent.com/34341691/39680528-1761e3d6-5178-11e8-99b5-713ce998cf04.png)

**Comment by mepalacios** [comment]
if it works, apparently it's a problem in my machine, I'm sorry
